name: Setup Configuration

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup configuration
        env:
          DATABRICKS_WAREHOUSE_ID: ${{ secrets.WAREHOUSE_ID }}
        run: |
          envsubst < test-project-streamlit-app/app.yaml > test-project-streamlit-app/app.processed.yaml
          mv test-project-streamlit-app/app.processed.yaml test-project-streamlit-app/app.yaml
      
      - name: Verify configuration (masked)
        run: |
          grep -v "DATABRICKS_WAREHOUSE_ID" test-project-streamlit-app/app.yaml
